// <auto-generated />
using EFCoreGalvanizeTeam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreGalvanizeTeam.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("EFCoreGalvanizeTeam.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "English I",
                            StudentId = 1,
                            Value = 90m
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Calculus II",
                            StudentId = 1,
                            Value = 70m
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Theater Appreciation",
                            StudentId = 2,
                            Value = 50m
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Dynamic Programming",
                            StudentId = 2,
                            Value = 85m
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "Data Structures",
                            StudentId = 2,
                            Value = 15m
                        },
                        new
                        {
                            Id = 6,
                            CourseName = "Senior Design I",
                            StudentId = 3,
                            Value = 97m
                        },
                        new
                        {
                            Id = 7,
                            CourseName = "Cloud Computing",
                            StudentId = 3,
                            Value = 75m
                        },
                        new
                        {
                            Id = 8,
                            CourseName = "Mixology",
                            StudentId = 5,
                            Value = 20m
                        },
                        new
                        {
                            Id = 9,
                            CourseName = "Mixology II",
                            StudentId = 5,
                            Value = 95m
                        },
                        new
                        {
                            Id = 10,
                            CourseName = "Mixology",
                            StudentId = 6,
                            Value = 16m
                        });
                });

            modelBuilder.Entity("EFCoreGalvanizeTeam.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 14,
                            Classification = 0,
                            FirstName = "Samuel",
                            LastName = "Adams"
                        },
                        new
                        {
                            Id = 2,
                            Age = 16,
                            Classification = 1,
                            FirstName = "Jack",
                            LastName = "Daniels"
                        },
                        new
                        {
                            Id = 3,
                            Age = 17,
                            Classification = 3,
                            FirstName = "Jim",
                            LastName = "Bean"
                        },
                        new
                        {
                            Id = 4,
                            Age = 15,
                            Classification = 2,
                            FirstName = "Johnnie",
                            LastName = "Walker"
                        },
                        new
                        {
                            Id = 5,
                            Age = 20,
                            Classification = 1,
                            FirstName = "Don",
                            LastName = "Julio"
                        },
                        new
                        {
                            Id = 6,
                            Age = 18,
                            Classification = 3,
                            FirstName = "Jose",
                            LastName = "Cuervo"
                        });
                });

            modelBuilder.Entity("EFCoreGalvanizeTeam.Grade", b =>
                {
                    b.HasOne("EFCoreGalvanizeTeam.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCoreGalvanizeTeam.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
